### ISSUE TITLE
What is the actual list of cpu attr values for <dllmap cpu="">  config?

### ISSUE THREAD

**Issue by devizer** [mono/mono.posix#16]
I've built and tested portable libMono.Unix.so for armel armv5 cpu.

How to specify it in the config?
What is the actual list of cpu attr values for <dllmap cpu="">  config?

man mono-config says only single arm 32 cpu:
_cpu
    This is the name of the architecture for which the mapping should be applied. Allowed values are: x86, x86-64, sparc, ppc, s390, s390x, arm, mips, alpha, hppa, ia64._

**Comment by devizer** [comment]
Here is the answer: https://github.com/mono/mono/blob/main/mono/metadata/mono-config.c

It seems mono runtime can't distinguish armel v5 and armhf v6|v7

**Comment by akoeplinger** [comment]
looks like you figured out the answer, closing this issue
