### ISSUE TITLE
runtimes/linux-x64/libMono.Unix.so is missing compiling asp.net...

### ISSUE THREAD

**Issue by jmoyola** [mono/mono.posix#29]
My app is created, compiled and executing in a linux-x64 mono platform under asp.net, but with nuget package (not with older mono.unix mono.posix mono dll) my app throw a exception when try to access to serial ports:

The type initializer for 'Mono.Unix.Native.Syscall' threw an exception. Exception calling to function 'GetFileStatus' in 'Mono.Unix'
   runtimes/linux-x64/libMono.Unix.so assembly:<unknown assembly> type:<unknown type> member:(null) Exception

app throw a exception can't found libMono.Unix.so static library.

Compiler don't find static library, but in bin folder and "runtimes/linux-x64" subfolders exists.

If have create a non asp.net app (a console app) and all run ok...

Issue can be for dynamic compilation in asp.net? i remember asp.net have a dynamic compiler and compile each asp.net controller in temporal folders...
if package try find "runtimes" folder like subfolder of temporal will can't find it...

I try to copy libMono.Unix.so in /usr/lib or /lib folder, but can't find it... (i think always try to find in subfolder runtimes)

Where can put libMono.Unix.so for find it...?

Thaks you,...

**Comment by akoeplinger** [comment]
Using classical asp.net with legacy mono is not supported, it should work with asp.net core on dotnet (core).
