### ISSUE TITLE
Is tcgetattr supported?

### ISSUE THREAD

**Issue by kjpgit** [mono/mono.posix#35]
I don't see it on http://docs.go-mono.com/?link=N%3aMono.Unix or in grep

I wrote a console app using Tmds.Linux, and it works great on Linux/WSL, but is not portable to Mac currently.

And the .net built-in console support does not seem sufficient.  I don't see how to force the tty back to 'echo' mode right before an execve.

**Comment by kjpgit** [comment]
It looks like this was using an ioctl under the hood.  Never mind.  I was confused because Tmds.Libc chooses to expose the tc* wrappers.

**Comment by akoeplinger** [comment]
It is not supported right now, it'd need to be added in Syscall.cs and presumable some native wrappers for the termios struct.

https://github.com/mono/mono.posix/blob/062156d94302990cf742883bc688a1c9a1982a9f/src/Mono.Unix/Mono.Unix.Native/Syscall.cs#L5025

**Comment by kjpgit** [comment]
I'm hacking around this limitation as follows:

execve("sh -c 'stty sane; exec $my_target_prog $my_args'")
